import { FormEvent, useEffect, useState } from 'react'
import { CalendarDays, Check, Scale, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Animal, Farm, StudListing } from '../types/database'

export default function BoarSelection({farm}:{farm:Farm}) {
  const [boars,setBoars]=useState<StudListing[]>([]),[females,setFemales]=useState<Animal[]>([]),[selected,setSelected]=useState<string[]>([])
  const [female,setFemale]=useState(''),[show,setShow]=useState(false),[planName,setPlanName]=useState(''),[objective,setObjective]=useState(''),[message,setMessage]=useState('')
  async function load(){const [{data:b},{data:f}]=await Promise.all([supabase.from('stud_listings').select('*').eq('farm_id',farm.id).order('boar_name'),supabase.from('animals').select('*').eq('farm_id',farm.id).in('sex',['sow','gilt']).eq('status','active').order('call_name')]);setBoars(b||[]);setFemales(f||[])}
  useEffect(()=>{load()},[farm.id])
  function toggle(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):v.length<3?[...v,id]:v)}
  async function createPlan(){setMessage('');if(!female||!selected.length){setMessage('Select a sow/gilt and at least one boar.');return}const {data,error}=await supabase.from('mating_plans').insert({farm_id:farm.id,female_animal_id:female,plan_name:planName||'Mating comparison',objectives:objective,status:'draft',selected_stud_listing_id:selected[0]}).select('id').single();if(error||!data){setMessage(error?.message||'Plan could not be created.');return}const rows=selected.map((id,i)=>({farm_id:farm.id,mating_plan_id:data.id,stud_listing_id:id,rank:i+1,estimated_cost:boars.find(x=>x.id===id)?.semen_price}));const result=await supabase.from('mating_plan_candidates').insert(rows);setMessage(result.error?.message||'Mating comparison saved directly to the sow planner. No breeding cycle was created.');if(!result.error){setSelected([]);setPlanName('');setObjective('')}}
  return <><div className="page-head"><div><p className="eyebrow">INDEPENDENT BOAR LIBRARY</p><h1>Boar Selection</h1></div><button className="button primary" onClick={()=>setShow(true)}>+ Add boar</button></div><p className="lead">Enter boars once, compare as many as three, and select them from any sow's reproduction plan. Boars and comparisons do not require a breeding cycle.</p>
  <section className="panel comparison-controls"><label>Sow or gilt<select value={female} onChange={e=>setFemale(e.target.value)}><option value="">Select female…</option>{females.map(x=><option value={x.id} key={x.id}>{x.call_name}</option>)}</select></label><label>Plan name<input value={planName} onChange={e=>setPlanName(e.target.value)} placeholder="Example: Tammy fall mating"/></label><label className="wide-control">Breeding objectives<input value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Bone, body, color, structure, growth…"/></label></section>
  {boars.length?<div className="selection-grid">{boars.map(x=><article onClick={()=>toggle(x.id)} className={selected.includes(x.id)?'selection-card selected':'selection-card'} key={x.id}><div className="select-check">{selected.includes(x.id)&&<Check size={16}/>}</div><span className="pill">{x.availability_status}</span><h2>{x.boar_name}</h2><p>{x.stud_name}</p><dl><dt>Breed</dt><dd>{x.breed||'—'}</dd><dt>Pedigree</dt><dd>{x.sire_name||'—'} × {x.dam_name||'—'}</dd><dt>Registration</dt><dd>{x.registration_number||'—'}</dd><dt>Semen</dt><dd>{x.semen_price==null?'—':`$${Number(x.semen_price).toFixed(2)}`}</dd><dt>Strengths</dt><dd>{x.strengths||'Not entered'}</dd></dl></article>)}</div>:<section className="empty"><div><CalendarDays/></div><h2>Build your boar library</h2><p>Add prospective boars with pedigree, registration, stud, semen price, and expected improvements.</p></section>}
  {boars.length>0&&<div className="sticky-action"><span><Scale size={18}/> {selected.length} of 3 selected</span><button className="button primary" onClick={createPlan}>Save mating comparison</button></div>}{message&&<p className="notice">{message}</p>}{show&&<BoarModal farm={farm} close={()=>setShow(false)} saved={()=>{setShow(false);load()}}/>}</>
}

function BoarModal({farm,close,saved}:{farm:Farm;close:()=>void;saved:()=>void}){const blank={boar_name:'',stud_name:'',breed:'',sire_name:'',dam_name:'',maternal_grandsire:'',registration_number:'',registration_association:'',ear_notch:'',owner_name:'',owner_number:'',semen_price:'',source_url:'',strengths:'',concerns:'',notes:'',availability_status:'available'};const[v,setV]=useState(blank),[error,setError]=useState('');const field=(k:keyof typeof blank,x:string)=>setV({...v,[k]:x});async function submit(e:FormEvent){e.preventDefault();const{error}=await supabase.from('stud_listings').insert({...v,farm_id:farm.id,semen_price:v.semen_price?Number(v.semen_price):null,last_verified_date:new Date().toISOString().slice(0,10)});if(error)setError(error.message);else saved()}return <div className="modal-backdrop"><section className="modal"><header><h2>Add prospective boar</h2><button className="icon-button" onClick={close}><X/></button></header><form onSubmit={submit} className="form-grid"><Input label="Boar name" value={v.boar_name} onChange={x=>field('boar_name',x)} required/><Input label="Boar stud" value={v.stud_name} onChange={x=>field('stud_name',x)} required/><Input label="Breed" value={v.breed} onChange={x=>field('breed',x)}/><Input label="Semen price" type="number" value={v.semen_price} onChange={x=>field('semen_price',x)} min="0" step=".01"/><Input label="Sire" value={v.sire_name} onChange={x=>field('sire_name',x)}/><Input label="Dam" value={v.dam_name} onChange={x=>field('dam_name',x)}/><Input label="Maternal grandsire" value={v.maternal_grandsire} onChange={x=>field('maternal_grandsire',x)}/><Input label="Registration association" value={v.registration_association} onChange={x=>field('registration_association',x)}/><Input label="Registration number" value={v.registration_number} onChange={x=>field('registration_number',x)}/><Input label="Ear notch" value={v.ear_notch} onChange={x=>field('ear_notch',x)}/><Input label="Owner of boar / service sire" value={v.owner_name} onChange={x=>field('owner_name',x)}/><Input label="Boar owner number" value={v.owner_number} onChange={x=>field('owner_number',x)}/><Input label="Catalog URL" type="url" value={v.source_url} onChange={x=>field('source_url',x)}/><div/><label className="full">Strengths / expected improvements<textarea value={v.strengths} onChange={e=>field('strengths',e.target.value)}/></label><label className="full">Concerns / mating cautions<textarea value={v.concerns} onChange={e=>field('concerns',e.target.value)}/></label><label className="full">Notes<textarea value={v.notes} onChange={e=>field('notes',e.target.value)}/></label>{error&&<p className="error full">{error}</p>}<div className="form-actions full"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button primary">Save boar</button></div></form></section></div>}
function Input({label,onChange,type='text',...props}:{label:string;onChange:(v:string)=>void;type?:string;[key:string]:unknown}){return <label>{label}<input type={type} {...props} onChange={e=>onChange(e.target.value)}/></label>}
