import { FormEvent, useEffect, useState } from 'react'
import { Baby, CalendarClock, CheckCircle2, Dna, Plus, Syringe, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { addDays } from '../lib/terminology'
import type { Animal, BreedingCycle, Farm, MatingPlan, StudListing } from '../types/database'

type EventKind = 'sync'|'breed'|'check'|'farrow'|null

export default function Reproduction({farm}:{farm:Farm}){
  const [cycles,setCycles]=useState<BreedingCycle[]>([]),[females,setFemales]=useState<Animal[]>([]),[boars,setBoars]=useState<StudListing[]>([]),[plans,setPlans]=useState<MatingPlan[]>([])
  const [showNew,setShowNew]=useState(false),[event,setEvent]=useState<{kind:EventKind;cycle:BreedingCycle|null}>({kind:null,cycle:null}),[message,setMessage]=useState('')
  async function load(){const[c,f,b,p]=await Promise.all([supabase.from('breeding_cycles').select('*,female:animals!breeding_cycles_female_animal_id_fkey(call_name),sire:stud_listings!breeding_cycles_sire_listing_id_fkey(boar_name)').eq('farm_id',farm.id).order('created_at',{ascending:false}),supabase.from('animals').select('*').eq('farm_id',farm.id).in('sex',['sow','gilt']).eq('status','active').order('call_name'),supabase.from('stud_listings').select('*').eq('farm_id',farm.id).order('boar_name'),supabase.from('mating_plans').select('*').eq('farm_id',farm.id).order('created_at',{ascending:false})]);setCycles((c.data||[]) as BreedingCycle[]);setFemales(f.data||[]);setBoars(b.data||[]);setPlans(p.data||[])}
  useEffect(()=>{load()},[farm.id])
  const active=cycles.filter(x=>!['completed','cancelled','open'].includes(x.status)), completed=cycles.filter(x=>['completed','cancelled','open'].includes(x.status))
  return <><div className="page-head"><div><p className="eyebrow">BREEDING THROUGH FARROWING</p><h1>Reproduction</h1></div><button className="button primary" onClick={()=>setShowNew(true)}><Plus size={17}/> New breeding cycle</button></div>
  <div className="stat-grid"><Stat label="Active cycles" value={active.length}/><Stat label="Confirmed pregnant" value={cycles.filter(x=>x.status==='confirmed_pregnant').length}/><Stat label="Expected farrowings" value={cycles.filter(x=>x.expected_birth_date&&!['completed','open'].includes(x.status)).length}/><Stat label="Completed cycles" value={completed.length}/></div>
  {active.length?<div className="cycle-list">{active.map(c=><CycleCard key={c.id} cycle={c} setEvent={kind=>setEvent({kind,cycle:c})}/>)}</div>:<section className="empty"><div><Dna/></div><h2>No active breeding cycles</h2><p>Create a cycle directly or from a saved mating comparison.</p></section>}
  {completed.length>0&&<section className="panel"><h2>Completed and closed cycles</h2>{completed.map(c=><div className="record-row" key={c.id}><strong>{c.female?.call_name||'Female'}</strong><span>{c.status.replaceAll('_',' ')}</span></div>)}</section>}
  {message&&<p className="notice">{message}</p>}{showNew&&<NewCycle farm={farm} females={females} boars={boars} plans={plans} close={()=>setShowNew(false)} saved={()=>{setShowNew(false);load()}}/>}{event.kind&&event.cycle&&<EventModal kind={event.kind} cycle={event.cycle} farm={farm} close={()=>setEvent({kind:null,cycle:null})} saved={msg=>{setMessage(msg);setEvent({kind:null,cycle:null});load()}}/>}</>
}

function CycleCard({cycle,setEvent}:{cycle:BreedingCycle;setEvent:(kind:Exclude<EventKind,null>)=>void}){return <article className="cycle-card"><div className="cycle-main"><span className="pill">{cycle.status.replaceAll('_',' ')}</span><h2>{cycle.female?.call_name||'Female'} × {cycle.sire?.boar_name||'Sire not selected'}</h2><p>Cycle started {formatDate(cycle.cycle_start_date)}{cycle.expected_birth_date&&<> • Expected farrowing <strong>{formatDate(cycle.expected_birth_date)}</strong></>}</p></div><div className="cycle-actions"><button onClick={()=>setEvent('sync')}><Syringe/> Synchronization</button><button onClick={()=>setEvent('breed')}><Dna/> Breeding</button><button onClick={()=>setEvent('check')}><CheckCircle2/> Pregnancy check</button><button onClick={()=>setEvent('farrow')}><Baby/> Farrowing</button></div></article>}

function NewCycle({farm,females,boars,plans,close,saved}:{farm:Farm;females:Animal[];boars:StudListing[];plans:MatingPlan[];close:()=>void;saved:()=>void}){const[female,setFemale]=useState(''),[boar,setBoar]=useState(''),[plan,setPlan]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[notes,setNotes]=useState(''),[error,setError]=useState('');function choosePlan(id:string){setPlan(id);const p=plans.find(x=>x.id===id);if(p){setFemale(p.female_animal_id);if(p.selected_stud_listing_id)setBoar(p.selected_stud_listing_id)}}async function submit(e:FormEvent){e.preventDefault();const{error}=await supabase.from('breeding_cycles').insert({farm_id:farm.id,female_animal_id:female,sire_listing_id:boar||null,mating_plan_id:plan||null,cycle_start_date:date,status:'planned',notes});if(error)setError(error.message);else saved()}return <Modal title="New breeding cycle" close={close}><form onSubmit={submit} className="form-grid"><label className="full">Saved mating plan (optional)<select value={plan} onChange={e=>choosePlan(e.target.value)}><option value="">Start without saved plan</option>{plans.filter(x=>x.status==='draft').map(x=><option value={x.id} key={x.id}>{x.plan_name||'Mating comparison'}</option>)}</select></label><label>Sow or gilt<select required value={female} onChange={e=>setFemale(e.target.value)}><option value="">Select…</option>{females.map(x=><option value={x.id} key={x.id}>{x.call_name}</option>)}</select></label><label>Selected boar<select value={boar} onChange={e=>setBoar(e.target.value)}><option value="">Not selected</option>{boars.map(x=><option value={x.id} key={x.id}>{x.boar_name} — {x.stud_name}</option>)}</select></label><Input label="Cycle start date" type="date" value={date} onChange={setDate} required/><div/><label className="full">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p className="error full">{error}</p>}<Actions close={close} label="Create cycle"/></form></Modal>}

function EventModal({kind,cycle,farm,close,saved}:{kind:Exclude<EventKind,null>;cycle:BreedingCycle;farm:Farm;close:()=>void;saved:(message:string)=>void}){if(kind==='sync')return <SyncEvent cycle={cycle} farm={farm} close={close} saved={saved}/>;if(kind==='breed')return <BreedEvent cycle={cycle} farm={farm} close={close} saved={saved}/>;if(kind==='check')return <PregnancyEvent cycle={cycle} farm={farm} close={close} saved={saved}/>;return <FarrowEvent cycle={cycle} close={close} saved={saved}/>}

function SyncEvent({cycle,farm,close,saved}:{cycle:BreedingCycle;farm:Farm;close:()=>void;saved:(m:string)=>void}){const[date,setDate]=useState(nowLocal()),[protocol,setProtocol]=useState('Matrix synchronization'),[product,setProduct]=useState('Matrix'),[dose,setDose]=useState(''),[notes,setNotes]=useState(''),[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();const{error}=await supabase.from('synchronization_events').insert({farm_id:farm.id,breeding_cycle_id:cycle.id,event_date:new Date(date).toISOString(),protocol_name:protocol,product_name:product,dose,notes});if(!error)await supabase.from('breeding_cycles').update({status:'synchronizing'}).eq('id',cycle.id);if(error)setError(error.message);else saved('Synchronization event recorded.')}return <Modal title="Record synchronization" close={close}><form onSubmit={submit} className="form-grid"><Input label="Date and time" type="datetime-local" value={date} onChange={setDate}/><Input label="Protocol" value={protocol} onChange={setProtocol}/><Input label="Product" value={product} onChange={setProduct}/><Input label="Dose" value={dose} onChange={setDose}/><label className="full">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p className="error full">{error}</p>}<Actions close={close} label="Save event"/></form></Modal>}

function BreedEvent({cycle,farm,close,saved}:{cycle:BreedingCycle;farm:Farm;close:()=>void;saved:(m:string)=>void}){const[date,setDate]=useState(nowLocal()),[service,setService]=useState('1'),[method,setMethod]=useState('artificial_insemination'),[batch,setBatch]=useState(''),[technician,setTechnician]=useState(''),[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();const eventDate=new Date(date).toISOString(),expected=addDays(eventDate.slice(0,10),114);const{error}=await supabase.from('breeding_events').insert({farm_id:farm.id,breeding_cycle_id:cycle.id,event_date:eventDate,service_number:Number(service),method,semen_batch:batch,technician});if(!error)await supabase.from('breeding_cycles').update({status:'bred',expected_birth_date:expected}).eq('id',cycle.id);if(error)setError(error.message);else saved(`Breeding recorded. Estimated farrowing date: ${formatDate(expected)}.`)}return <Modal title="Record breeding" close={close}><form onSubmit={submit} className="form-grid"><Input label="Date and time" type="datetime-local" value={date} onChange={setDate}/><Input label="Service number" type="number" min="1" value={service} onChange={setService}/><label>Method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="artificial_insemination">Artificial insemination</option><option value="natural_service">Natural service</option></select></label><Input label="Semen batch / collection" value={batch} onChange={setBatch}/><Input label="Technician" value={technician} onChange={setTechnician}/>{error&&<p className="error full">{error}</p>}<Actions close={close} label="Save breeding"/></form></Modal>}

function PregnancyEvent({cycle,farm,close,saved}:{cycle:BreedingCycle;farm:Farm;close:()=>void;saved:(m:string)=>void}){const[date,setDate]=useState(new Date().toISOString().slice(0,10)),[method,setMethod]=useState('Ultrasound'),[result,setResult]=useState('positive'),[notes,setNotes]=useState(''),[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();const{error}=await supabase.from('pregnancy_checks').insert({farm_id:farm.id,breeding_cycle_id:cycle.id,check_date:date,method,result,notes});if(!error)await supabase.from('breeding_cycles').update({status:result==='positive'?'confirmed_pregnant':result==='negative'?'open':'bred'}).eq('id',cycle.id);if(error)setError(error.message);else saved(`Pregnancy check recorded: ${result}.`)}return <Modal title="Record pregnancy check" close={close}><form onSubmit={submit} className="form-grid"><Input label="Check date" type="date" value={date} onChange={setDate}/><Input label="Method" value={method} onChange={setMethod}/><label>Result<select value={result} onChange={e=>setResult(e.target.value)}><option value="positive">Positive</option><option value="negative">Negative/open</option><option value="inconclusive">Inconclusive</option></select></label><label className="full">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p className="error full">{error}</p>}<Actions close={close} label="Save check"/></form></Modal>}

function FarrowEvent({cycle,close,saved}:{cycle:BreedingCycle;close:()=>void;saved:(m:string)=>void}){const[date,setDate]=useState(nowLocal()),[total,setTotal]=useState('0'),[alive,setAlive]=useState('0'),[stillborn,setStillborn]=useState('0'),[mummies,setMummies]=useState('0'),[assisted,setAssisted]=useState(false),[notes,setNotes]=useState(''),[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();const{error}=await supabase.rpc('create_birth_group',{p_cycle_id:cycle.id,p_event_date:new Date(date).toISOString(),p_total_born:Number(total),p_born_alive:Number(alive),p_stillborn:Number(stillborn),p_mummified:Number(mummies),p_assistance_required:assisted,p_notes:notes||null});if(error)setError(error.message);else saved(`Farrowing saved and ${alive} individual piglet record(s) created.`)}return <Modal title="Record farrowing & create litter" close={close}><form onSubmit={submit} className="form-grid"><Input label="Farrowing date and time" type="datetime-local" value={date} onChange={setDate}/><Input label="Total born" type="number" min="0" value={total} onChange={setTotal}/><Input label="Born alive" type="number" min="0" value={alive} onChange={setAlive}/><Input label="Stillborn" type="number" min="0" value={stillborn} onChange={setStillborn}/><Input label="Mummified" type="number" min="0" value={mummies} onChange={setMummies}/><label className="check-label"><input type="checkbox" checked={assisted} onChange={e=>setAssisted(e.target.checked)}/> Assistance required</label><label className="full">Farrowing notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><p className="notice full">Saving will create one editable animal profile for every piglet recorded as born alive.</p>{error&&<p className="error full">{error}</p>}<Actions close={close} label="Save farrowing & create litter"/></form></Modal>}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><section className="modal"><header><h2>{title}</h2><button className="icon-button" onClick={close}><X/></button></header>{children}</section></div>}
function Actions({close,label}:{close:()=>void;label:string}){return <div className="form-actions full"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button primary">{label}</button></div>}
function Input({label,onChange,type='text',...props}:{label:string;onChange:(v:string)=>void;type?:string;[key:string]:unknown}){return <label>{label}<input type={type} {...props} onChange={e=>onChange(e.target.value)}/></label>}
function Stat({label,value}:{label:string;value:number}){return <div className="stat"><strong>{value}</strong><span>{label}</span></div>}
function formatDate(value:string){return new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function nowLocal(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
